spring.application.name=Super-A

# MongoDB Remote Configuration
spring.data.mongodb.uri=mongodb://supera_user:SuperA2025!@172.31.42.55:27017/supera?authSource=supera
spring.data.mongodb.host=172.31.42.55
spring.data.mongodb.port=27017
spring.data.mongodb.database=supera
spring.data.mongodb.authentication-database=supera
spring.data.mongodb.username=supera_user
spring.data.mongodb.password=SuperA2025!

# Prevent connection to localhost
spring.data.mongodb.auto-index-creation=true

# AWS S3 Configuration
aws.s3.bucket=my-store-images-prod
aws.s3.region=us-east-2
aws.s3.cloud-front-url=https://d7hb0qlam0ifv.cloudfront.net
aws.s3.cloud-front-distribution-id=E1234567890

# File Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:noreply@supera.com}
spring.mail.password=${MAIL_PASSWORD:dummy-password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# Alert emails recipients
alerts.email.recipients=${ALERT_EMAIL_RECIPIENTS:julianpintoramos88@gmail.com,superaragonoficial@gmail.com}
